nodeLinker: node-modules

nmMode: "hardlinks-global"

npmRegistryServer: "https://registry.npmjs.org"

# Muting YN0076 - INCOMPATIBLE_ARCHITECTURE
# https://yarnpkg.com/advanced/error-codes#yn0076---incompatible_architecture
logFilters:
  - code: "YN0076"
    level: "discard"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.1.0.cjs
